version: '3.1'

services:

  api:
    build: docker/apache
    container_name: solcre-express-lambda
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/apache/ini/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - ./docker/apache/ini/xdebug-php-ini-overrides.ini:/usr/local/etc/php/conf.d/xdebug-php-ini-overrides.ini
    expose:
      # xdebug port
      - 9001
    ports:
      - "${DOCKER_PORT_API}:80"
